sudo: required
services:
    - docker

before_install:
    - docker build -t b3a3a/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true b3a3a/react-test yarn test -- --coverage

after_success:
    - docker build -t b3a3a/multi-client ./client
    - docker build -t b3a3a/multi-eginx ./nginx
    - docker build -t b3a3a/multi-server ./server
    - docker build -t b3a3a/multi-worker ./worker
    # Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push b3a3a/multi-client
    - docker push b3a3a/multi-eginx
    - docker push b3a3a/multi-server
    - docker push b3a3a/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucker_name: "elasticbeanstalk-ap-southeast-1-742347738784"
    bucker_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY