sudo: required
services:
    - docker

before_install:
    - docker build -t b3a3a/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true b3a3a/react-test yarn test -- --coverage

after_success:
    - docker build -t b3a3a/multi-client ./client
    - docker build -t b3a3a/multi-eginx ./nginx
    - docker build -t b3a3a/multi-server ./server
    - docker build -t b3a3a/multi-worker ./worker
    # Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push b3a3a/multi-client
    - docker push b3a3a/multi-eginx
    - docker push b3a3a/multi-server
    - docker push b3a3a/multi-worker