sudo: required
services:
    - docker

before_install:
    - docker build -t ybtooaceras/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ybtooaceras/react-test yarn test -- --coverage

after_success:
    - docker build -t ybtooaceras/multi-client ./client
    - docker build -t ybtooaceras/multi-eginx ./nginx
    - docker build -t ybtooaceras/multi-server ./server
    - docker build -t ybtooaceras/multi-worker ./worker
    # Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push ybtooaceras/multi-client
    - docker push ybtooaceras/multi-eginx
    - docker push ybtooaceras/multi-server
    - docker push ybtooaceras/multi-worker